name: music
description: A new Flutter application.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  flutter_spinkit: ^4.1.2
  connectivity: ^2.0.0
  fluttertoast: ^7.1.1
  shared_preferences: ^0.5.12+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - localStorage/

